name: Initialize

on:
  workflow_dispatch:

jobs:
  initialize:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          persist-credentials: false
      
      - name: Install requirements
        run: |
          sudo apt install -y wget unzip
      
      - name: Download Spend package
        run: |
          wget -q -O spend.zip https://circuitscan-artifacts.s3.us-west-2.amazonaws.com/build/spend-nice-olive-raven/pkg.zip

      - name: Unzipping Spend package
        run: |
          mkdir spend && unzip spend.zip '*.zkey' '*.r1cs' -d spend && rm -rf spend.zip

      - name: Show inside
        run: |
          tree spend/

      - name: Downloading ptau_18
        run: |
          wget -q https://storage.googleapis.com/zkevm/ptau/powersOfTau28_hez_final_18.ptau

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install SnarkJS
        run: |
          npm i -g snarkjs

      - name: Verify the Spend's initial zkey
        run: |
          snarkjs zkey verify spend/build/verify_circuit/verify_circuit.r1cs powersOfTau28_hez_final_18.ptau spend/build/verify_circuit/groth16_pkey.zkey

      - name: Remove ptau_18
        run: |
          rm -rf powersOfTau28_hez_final_18.ptau

      - name: Download Proof of Burn package
        run: |
          wget -q -O proof_of_burn.zip https://circuitscan-artifacts.s3.us-west-2.amazonaws.com/build/proofofburn-unconscious-sapphire-gorilla/pkg.zip

      - name: Unzipping Proof-of-Burn package
        run: |
          mkdir proof_of_burn && unzip proof_of_burn.zip '*.zkey' '*.r1cs' -d proof_of_burn

      - name: Downloading ptau_24
        run: |
          wget -q https://storage.googleapis.com/zkevm/ptau/powersOfTau28_hez_final_24.ptau

      - name: Verify the Proof-of-Burn's initial zkey
        run: |
          snarkjs zkey verify proof_of_burn/build/verify_circuit/verify_circuit.r1cs powersOfTau28_hez_final_24.ptau proof_of_burn/build/verify_circuit/groth16_pkey.zkey

      - name: Download GitHub CLI
        run: |
          wget -q https://github.com/cli/cli/releases/download/v2.76.1/gh_2.76.1_linux_amd64.deb
        
      - name: Install GitHub CLI
        run: |
          sudo dpkg -i gh_2.76.1_linux_amd64.deb