name: Initialize circuit data

on:
  workflow_dispatch:

jobs:
  initialize_circuit_data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          persist-credentials: false
      
      - name: Install requirements
        run: |
          sudo apt install -y wget unzip
      
      - name: Download Spend package
        run: |
          wget -q -O spend.zip https://circuitscan-artifacts.s3.us-west-2.amazonaws.com/build/spend-unlikely-white-gayal/pkg.zip

      - name: Unzipping Spend package
        run: |
          mkdir spend && unzip spend.zip '*.r1cs' '*_cpp/*' -d spend && rm -rf spend.zip
        
      - name: Download Proof-of-Burn package
        run: |
          wget -q -O proof_of_burn.zip https://circuitscan-artifacts.s3.us-west-2.amazonaws.com/build/proofofburn-alone-white-earwig/pkg.zip

      - name: Unzipping Proof-of-Burn package
        run: |
          mkdir proof_of_burn && unzip proof_of_burn.zip '*.r1cs' '*_cpp/*' -d proof_of_burn && rm -rf proof_of_burn.zip

      - name: Packaging parameters
        run: |
          mv spend/build/verify_circuit/verify_circuit.r1cs spend.r1cs
          mv proof_of_burn/build/verify_circuit/verify_circuit.r1cs proof_of_burn.r1cs
          mv spend/build/verify_circuit/verify_circuit_cpp/verify_circuit.dat spend.dat
          mv proof_of_burn/build/verify_circuit/verify_circuit_cpp/verify_circuit.dat proof_of_burn.dat
          tar czf spend_witness_gen.tar.gz spend/build/verify_circuit/verify_circuit_cpp/*
          tar czf proof_of_burn_witness_gen.tar.gz proof_of_burn/build/verify_circuit/verify_circuit_cpp/*
          gzip spend.r1cs
          gzip proof_of_burn.r1cs

      - name: Download GitHub CLI
        run: |
          wget -q https://github.com/cli/cli/releases/download/v2.76.1/gh_2.76.1_linux_amd64.deb
        
      - name: Install GitHub CLI
        run: |
          sudo dpkg -i gh_2.76.1_linux_amd64.deb

      - name: Login
        run: |
          echo "${{secrets.gh_token}}" | gh auth login --with-token
      
      - name: Create release
        run: |
          gh release create circuit_data --title "R1CS files and witness-generators" --notes "R1CS files and witness-generators" spend_witness_gen.tar.gz spend.r1cs.gz spend.dat proof_of_burn_witness_gen.tar.gz proof_of_burn.r1cs.gz proof_of_burn.dat