name: Participate

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  participate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install SnarkJS
        run: |
          npm i -g snarkjs
          
      - name: Install requirements
        run: |
          sudo apt install -y wget

      - name: Download GitHub CLI
        run: |
          wget https://github.com/cli/cli/releases/download/v2.76.1/gh_2.76.1_linux_386.deb

      - name: Download GitHub CLI
        run: |
          dpkg -i gh_2.76.1_linux_386.deb

      - name: Contribute
        run: |
          make contribute WGET_ARGS=-q